name: surgeonadaptrl
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - numpy=1.24.4
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - pillow=9.5.0
  - pyyaml=6.0
  - opencv=4.7.0
  - tensorboard=2.13.0
